# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.8'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'rails', '~> 6.1.4', '>= 6.1.4.1'

group :development, :test do
  gem 'factory_bot_rails', '~> 6.1.0'
  gem 'pry-byebug'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'rubocop'
  gem 'spring'
end

group :test do
  gem 'database_cleaner', '~> 1.8'
  gem 'rspec-rails', '~> 5.0.0'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
